import '@babel/polyfill'

import './styles/base.css'
import './styles/colors.css'
import './styles/layout.css'
import './styles/typography.css'
import './styles/ui.css'
import './styles/modules.css'
import './styles/utils.css'
import './styles/modules/header.css'
import './styles/modules/footer.css'
import './styles/modules/landing.css'

import './scripts/gtm'
import '../old/scripts/menu'
import '../old/scripts/accordion'
import '../old/scripts/pricing'